# Generated by Django 4.2.1 on 2023-05-16 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('tags', models.TextField()),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(auto_created=True)),
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jypapp.employee')),
                ('post_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jypapp.post')),
            ],
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(auto_created=True)),
                ('keyword', models.CharField(max_length=200)),
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jypapp.employee')),
            ],
        ),
    ]
